name: macOS Metal Clang

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

jobs:
  macOS-Metal-Clang:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: macOS
      SKU: macOS
      Test-Clang: On
      TestTarget: check-hlsl-clang-mtl
