name: macOS Metal DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

jobs:
  macOS-Metal-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: macOS
      SKU: macOS
      Test-Clang: Off
      TestTarget: check-hlsl-mtl
