name: macOS Metal DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '0 */2 * * *' # run every 2 hours

jobs:
  macOS-Metal-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: macOS
      Test-Clang: Off
      TestTarget: check-hlsl-mtl
