name: macOS Metal DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

  pull_request:
    branches:
      - main

jobs:
  macOS-Metal-DXC-PR:
    if: ${{ github.event.issue.pull_request }}
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: macOS
      SKU: macOS
      Test-Clang: Off
      TestTarget: check-hlsl-mtl
      HLSLTest-branch: ${{ github.event.pull_request.head.sha }}
  macOS-Metal-DXC:
    if: ${{ !github.event.issue.pull_request }}
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: macOS
      SKU: macOS
      Test-Clang: Off
      TestTarget: check-hlsl-mtl
