name: Windows Vulkan Intel DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

jobs:
  Windows-VK-Intel-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-vk
