name: Windows D3D12 Warp Clang

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '0,30 * * * *' # run every 30 minutes

jobs:
  Windows-D3D12-Warp-Clang:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      Test-Clang: On
      TestTarget: check-hlsl-clang-warp-d3d12
