name: Windows Vulkan Intel DXC

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

  pull_request:
    branches:
      - main

jobs:
  Windows-VK-Intel-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-vk
      HLSLTest-branch: ${{ github.ref }}
