name: Windows D3D12 Intel DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

  pull_request:
    branches:
      - main

jobs:
  Windows-D3D12-Intel-DXC-PR:
    if: ${{ github.event.issue.pull_request }}
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-d3d12
      HLSLTest-branch: ${{ github.event.pull_request.head.sha }}
  Windows-D3D12-Intel-DXC:
    if: ${{ !github.event.issue.pull_request }}
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-d3d12
