name: Windows D3D12 NVIDIA Clang

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 0-12 * * *' # run every 30 minutes overnight

jobs:
  Windows-D3D12-NVIDIA-Clang:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-NV
      Test-Clang: On
      TestTarget: check-hlsl-clang-d3d12
