name: windows-Intel-nightly

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '0 */6 * * *' # run every 6 hours

jobs:
  windows-nightly:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
