name: Windows D3D12 Warp DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '0,30 * * * *' # run every 30 minutes

jobs:
  Windows-D3D12-Warp-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-warp-d3d12
