name: Windows D3D12 Warp DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

jobs:
  Windows-D3D12-Warp-DXC-PR:
    if: ${{ github.event.issue.pull_request }}
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-warp-d3d12
      HLSLTest-branch: ${{ github.event.pull_request.head.sha }}
  Windows-D3D12-Warp-DXC:
    if: ${{ !github.event.issue.pull_request }}
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-warp-d3d12
