name: windows-Intel-dxc-only

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '0 */12 * * *' # run every 12 hours

jobs:
  windows-Intel-dxc-only:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      Test-Clang: Off
      BuildType: Debug
