name: Windows D3D12 Warp DXC

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

  pull_request:
    branches:
      - main

jobs:
  Windows-D3D12-Warp-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-warp-d3d12
      HLSLTest-branch: ${{ github.ref }}
