name: Windows Vulkan NVIDIA Clang

permissions:
  contents: read
  checks: write

on:
  schedule:
    - cron: '0 12-24 * * *' # run hourly over night

jobs:
  Windows-VK-Intel-Clang:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-NV
      Test-Clang: On
      TestTarget: check-hlsl-clang-vk
